#!/usr/bin/bash

# xrdb -load .Xresources

# picom -b --config /home/achuie/.config/picom/picom.conf

xset -dpms
xset s off

# export GDK_DPI_SCALE=1.5
# export QT_SCALE_FACTOR=1.5

export TERMINAL=wezterm

# export GTK_IM_MODULE=fcitx
# export QT_IM_MODULE=fcitx
# export XMODIFIERS=@im=fcitx

# bash /home/achuie/.screenlayout/default.sh
# bash /home/achuie/.fehbg

# fcitx &

# dunst &

export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_DATA_DIRS="$XDG_DATA_DIRS:/usr/share:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share"

exec i3
