# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/90f6abc1-1b2e-444c-800b-68a041d62fdb";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" ];
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/4E7A-8F9F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    {
      device = "ztank/home";
      fsType = "zfs";
    };

  fileSystems."/media" =
    {
      device = "ztank/media";
      fsType = "zfs";
    };

  fileSystems."/share" =
    {
      device = "ztank/share";
      fsType = "zfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/f9d5b16c-14c9-4935-96dd-90020c8264cf"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.amdgpu = {
    opencl.enable = true;
    amdvlk.enable = true;
  };
  hardware.graphics.extraPackages = with pkgs; [ rocmPackages.clr.icd ];
  environment.variables = { ROC_ENABLE_PRE_VEGA = "1"; };
}
